import {
  WISHLIST_WITH_PARAMS,
  BASKET_WITH_PARAMS,
  PRODUCT_WITH_PARAMS,
  SEARCH_WITH_PARAMS,
} from '.'

export default {
  wishlist: WISHLIST_WITH_PARAMS,
  basket: BASKET_WITH_PARAMS,
  product: PRODUCT_WITH_PARAMS,
  search: SEARCH_WITH_PARAMS,
}
